name: AETHERA Local
values:
  - key: base_url
    value: 'http://127.0.0.1:8000/api/v1'
  - key: access_token
    value: ''
  - key: refresh_token
    value: ''
  - key: workspace_id
    value: ''
  - key: folder_id
    value: ''
  - key: file_id
    value: ''
  - key: share_id
    value: ''
  - key: user_id
    value: ''
